import mongoose from "mongoose";

const exampleSchema = new mongoose.Schema(
  {
    input: { type: String, required: true },
    output: { type: String, required: true },
    explanation: { type: String, default: "" },
  },
  { _id: false }
);

const testCaseSchema = new mongoose.Schema(
  {
    // function arguments as JSON values, e.g. [[2,7,11,15], 9]
    args: { type: [mongoose.Schema.Types.Mixed], required: true },
    // canonical expected output, e.g. "[0,1]" or "true"
    expected: { type: String, required: true },
  },
  { _id: false }
);

const problemSchema = new mongoose.Schema(
  {
    slug: { type: String, required: true, unique: true, index: true },
    title: { type: String, required: true },
    difficulty: {
      type: String,
      enum: ["Easy", "Medium", "Hard", "Expert"],
      required: true,
      index: true,
    },
    tags: { type: [String], default: [], index: true },

    // where the problem came from — keeps Codeforces, in-house, and
    // AI-generated content cleanly separated in the same collection
    source: {
      type: String,
      enum: ["custom", "codeforces", "ai_generated"],
      default: "custom",
      index: true,
    },
    // Codeforces identity: "contestId-index" (e.g. "4-A"), unique per problem
    externalId: { type: String, default: "", index: true, unique: true, sparse: true },
    contestId: { type: Number, default: null },
    index: { type: String, default: "" },
    // Codeforces rating (800..3500); in-house problems may leave it null
    rating: { type: Number, default: null, index: true },
    // external link for Codeforces problems (we do not copy CF statements)
    url: { type: String, default: "" },
    solvedCount: { type: Number, default: 0 },

    // --- in-house / judge fields (optional for external problems) ---
    description: { type: String, default: "" }, // markdown-ish
    constraints: { type: [String], default: [] },
    examples: { type: [exampleSchema], default: [] },
    // language -> starter code (generated by services/problems/codegen.service.js)
    starterCode: { type: mongoose.Schema.Types.Mixed, default: {} },
    // canonical expected output for the sample tests (shared across languages)
    expectedOutput: { type: String, default: "" },
    // sample test cases (embedded in the starter harness)
    testCases: { type: [testCaseSchema], default: [] },
    // additional tests used only by the judge/submit path
    hiddenTestCases: { type: [testCaseSchema], default: [] },
    // grounding material for AI code review
    solutionApproach: { type: String, default: "" },
    // codegen spec (fn name, param/return types) used to rebuild judge harnesses
    codegen: { type: mongoose.Schema.Types.Mixed, default: null },
    // sort order: in-house problems use order; Codeforces problems store rating here too
    order: { type: Number, default: 0 },
  },
  { timestamps: true }
);

problemSchema.index({ title: "text", description: "text", tags: 1 });
// combined filter index for the question-bank API
problemSchema.index({ source: 1, difficulty: 1, rating: 1 });
problemSchema.index({ title: 1, source: 1 });

export default mongoose.model("Problem", problemSchema);
